[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "hrss"
version = "1.0.0"
description = "High-Res Severe Storm (HRSS) dataset helpers"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Your Name" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy>=1.22",
  "pandas>=2.0",
  "h5py>=3.8",
  "matplotlib>=3.7",
]

[project.optional-dependencies]
viz = ["matplotlib"]
notebooks = ["jupyter", "ipykernel"]

[project.urls]
Homepage = "https://github.com/<your-username>/hrss"
Repository = "https://github.com/<your-username>/hrss"

[tool.hatch.build.targets.wheel]
packages = ["src/hrss"]
